language: python

cache: pip

dist: trusty

addons:
  postgresql: "9.5"

sudo: required

python:
  - "3.6"

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  # Datacube system dependencies (gdal and netcdf)
  - sudo apt-get install --yes libhdf5-serial-dev libnetcdf-dev
  - sudo apt-get install --yes libgdal1-dev
  # POstgis dependencies
  - sudo apt-get install --yes libjson-c-dev postgresql-server-dev-9.5
  # Download and compile postgis
  - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
  - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)
  # Python (numpy headers required for rasterio)
  - pip install -U pip
  - pip install numpy
  - pip install GDAL==$(gdal-config --version) --global-option=build_ext --global-option="-I/usr/include/gdal"
  - ./travis_setup.py

env:
  - SECRET_KEY=key

install:
  - pip install -e .

before_script:
  - psql -U postgres -c "create extension postgis"
  - createdb datacube
  - datacube -v system init

script:
  - python setup.py test

warnings_are_errors: true

notifications:
  email: false
