language: python

cache: pip

dist: trusty

addons:
  postgresql: "9.5"

sudo: required

python:
  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  # Datacube system dependencies (gdal and netcdf)
  - sudo apt-get install --yes libhdf5-serial-dev libnetcdf-dev
  - sudo apt-get install --yes libgdal1-dev
  # POstgis dependencies
  - sudo apt-get install --yes libjson-c-dev postgresql-server-dev-9.5
  - sudo apt-get install --yes libproj-dev
  # Download and compile postgis
  - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
  - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)
  # Python (numpy headers required for rasterio)
  - pip install -U pip
  - pip install numpy
  - pip install GDAL==1.10.0 --global-option=build_ext --global-option="-I/usr/include/gdal"
  - pip install datacube==1.6.0
  - pip install xgboost
  - pip install sqlalchemy==1.2.18
  - ./travis_setup.py

env:
  - SECRET_KEY=key

install:
  - pip install '.[all]'

before_script:
  - psql -U postgres -c "create extension postgis"
  - createdb datacube
  - datacube -v system init

script:
  - python setup.py test

after_success:
  - pip install -r docs/requirements.txt 
  - git checkout -b gh-pages origin/gh-pages
  - rm -rf *
  - git checkout develop docs madmex
  - git reset HEAD
  - cd docs
  - make html
  - cd ..
  - mv -f docs/_build/html/* .
  - touch .nojekyll
  - rm -rf madmex docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: develop

warnings_are_errors: true

notifications:
  email: false
