services:
  - docker

before_script:
  - docker pull madmex/travis_antares3:v1

script:
  - docker run --rm -it --name travis-madmex-test --hostname madmex madmex/travis_antares3:v1 /bin/bash -c 'git clone --single-branch -b training-data-model-fit https://github.com/CONABIO/antares3.git /home/madmex_user/training-data-model-fit && /home/madmex_user/training-data-model-fit/travis_setup.py && cd /home/madmex_user/training-data-model-fit/ && sudo -u madmex_user python3.6 setup.py test'

after_success:
  - pip install -r docs/requirements.txt 
  - git checkout -b gh-pages origin/gh-pages
  - rm -rf *
  - git checkout develop docs madmex
  - git reset HEAD
  - cd docs
  - make html
  - cd ..
  - mv -f docs/_build/html/* .
  - touch .nojekyll
  - rm -rf madmex docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: develop

warnings_are_errors: true

notifications:
  email: false
