language: python

cache: pip

dist: xenial

python:
- "3.6"

services:
  - docker
env:
  - antares_branch=$TRAVIS_BRANCH datacube_branch=develop travis_docker_image=madmex/travis_antares3:v2
  
before_install:
  - sudo apt-get --yes --force-yes update -qq
  - pip install -U pip

before_script:
  - docker pull $travis_docker_image

  
script:
  - docker run --rm -it -e antares_branch=$antares_branch -e datacube_branch=$datacube_branch $travis_docker_image /bin/bash -c 'git clone --single-branch -b $antares_branch https://github.com/CONABIO/antares3.git /home/madmex_user/branch && /home/madmex_user/branch/travis_setup.py && sudo service postgresql start && sudo -u postgres createdb datacube && source /home/madmex_user/.profile && pip3.6 install --user git+https://github.com/opendatacube/datacube-core.git@$datacube_branch --no-deps --upgrade && datacube system init && cd /home/madmex_user/branch && python3.6 setup.py test' 


after_success:
  - pip install -r docs/requirements.txt 
  - git checkout -b gh-pages origin/gh-pages
  - rm -rf *
  - git checkout develop docs madmex
  - git reset HEAD
  - cd docs
  - make html
  - cd ..
  - mv -f docs/_build/html/* .
  - touch .nojekyll
  - rm -rf madmex docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: develop

warnings_are_errors: true

notifications:
  email: false
