id: {{ id }}
extent:
  center_dt: '2000-02-11'
  coord:
    ll: {lat: {{ ll_lat }}, lon: {{  ll_lon }} }
    lr: {lat: {{ lr_lat }}, lon: {{  lr_lon }} }
    ul: {lat: {{ ul_lat }}, lon: {{  ul_lon }} }
    ur: {lat: {{ ur_lat }}, lon: {{  ur_lon }} }
  from_dt: '2000-02-11'
  to_dt: '2000-02-22'
format: {name: GEOTIFF}
grid_spatial:
  projection:
    geo_ref_points:
      ll: {x: {{ ll_lon }}, y: {{ ll_lat }} }
      lr: {x: {{ lr_lon }}, y: {{ lr_lat }} }
      ul: {x: {{ ul_lon }}, y: {{ ul_lat }} }
      ur: {x: {{ ur_lon }}, y: {{ ur_lat }} }
    spatial_reference: {{ crs }}
image:
  bands:
    elevation: {layer: 1, path: "{{ elevation }}" }
    slope: {layer: 1, path: "{{ slope }}" }
    aspect: {layer: 1, path: "{{ aspect }}" }
instrument: {name: SIR}
lineage:
  source_datasets: {}
platform: {code: Space Shuttle Endeavour} 
processing_level: modelled
product_type: DEM 

