# Generated by Django 2.0 on 2017-12-12 17:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='madmex.Country')),
            ],
        ),
    ]
