# Generated by Django 2.0 on 2017-12-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0002_footprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='footprint',
            name='in_region',
            field=models.IntegerField(default=0),
        ),
    ]
