# Generated by Django 2.0 on 2017-12-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0003_footprint_in_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('downloaded', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='footprint',
            name='in_region',
        ),
    ]
