# Generated by Django 2.0 on 2017-12-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0004_auto_20171219_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
