# Generated by Django 2.0 on 2018-01-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0006_auto_20180116_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
