# Generated by Django 2.0 on 2018-01-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0008_auto_20180116_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
