# Generated by Django 2.0 on 2018-01-19 16:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0009_auto_20180117_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('region', models.ManyToManyField(to='madmex.Region')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madmex.Tag')),
            ],
        ),
    ]
