# Generated by Django 2.0 on 2018-01-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0010_tag_training'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Training',
            new_name='Object',
        ),
    ]
