# Generated by Django 2.0 on 2018-01-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0011_auto_20180119_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='region',
            new_name='regions',
        ),
    ]
