# Generated by Django 2.0 on 2018-01-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0012_auto_20180119_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='key',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
