# Generated by Django 2.0 on 2018-01-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0013_auto_20180119_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='key',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
