# Generated by Django 2.0 on 2018-01-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0014_auto_20180119_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='tag',
        ),
        migrations.AddField(
            model_name='object',
            name='tags',
            field=models.ManyToManyField(to='madmex.Tag'),
        ),
    ]
