# Generated by Django 2.0 on 2018-01-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0015_auto_20180119_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
