# Generated by Django 2.0 on 2018-02-02 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0017_object_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('path', models.CharField(max_length=100, unique=True)),
                ('training_set', models.CharField(max_length=100, unique=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=None, max_length=50)),
                ('value', models.CharField(default=None, max_length=150)),
                ('model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='madmex.Model')),
            ],
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='TrainTag',
        ),
        migrations.AddField(
            model_name='object',
            name='prediction_tags',
            field=models.ManyToManyField(default=None, to='madmex.PredictTag'),
        ),
    ]
