# Generated by Django 2.0 on 2018-02-08 18:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0018_auto_20180202_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.CharField(default=None, max_length=100)),
                ('prediction_tags', models.ManyToManyField(default=None, to='madmex.PredictTag')),
                ('regions', models.ManyToManyField(to='madmex.Region')),
            ],
        ),
        migrations.RemoveField(
            model_name='object',
            name='prediction_tags',
        ),
    ]
