# Generated by Django 2.0 on 2018-02-08 18:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0019_auto_20180208_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.CharField(default=None, max_length=100)),
                ('regions', models.ManyToManyField(to='madmex.Region')),
                ('training_tags', models.ManyToManyField(to='madmex.TrainTag')),
            ],
        ),
        migrations.RemoveField(
            model_name='object',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='object',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Object',
        ),
    ]
