# Generated by Django 2.0 on 2018-02-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0020_auto_20180208_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='recipe',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
