# Generated by Django 2.0 on 2018-02-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0021_model_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainobject',
            name='training_set',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='model',
            name='recipe',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
