# Generated by Django 2.0 on 2018-02-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0022_auto_20180226_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictobject',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='trainobject',
            name='dataset',
        ),
        migrations.AddField(
            model_name='footprint',
            name='sensor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='predictobject',
            name='training_set',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='model',
            name='path',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='training_set',
            field=models.CharField(max_length=100),
        ),
    ]
