# Generated by Django 2.0.1 on 2018-03-07 21:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0023_auto_20180227_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictobject',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
        migrations.AlterField(
            model_name='trainobject',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
