# Generated by Django 2.0.1 on 2018-03-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0025_auto_20180307_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainobject',
            name='filename',
            field=models.CharField(default='', max_length=200),
        ),
    ]
