# Generated by Django 2.0 on 2018-03-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0027_auto_20180308_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictobject',
            name='prediction_tags',
            field=models.ManyToManyField(through='madmex.PredictClassification', to='madmex.Tag'),
        ),
        migrations.AddField(
            model_name='trainobject',
            name='training_tags',
            field=models.ManyToManyField(through='madmex.TrainClassification', to='madmex.Tag'),
        ),
    ]
