# Generated by Django 2.0 on 2018-03-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0028_auto_20180308_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictobject',
            name='training_set',
        ),
        migrations.RemoveField(
            model_name='trainobject',
            name='training_set',
        ),
        migrations.AlterField(
            model_name='trainobject',
            name='creation_year',
            field=models.CharField(default='2015', max_length=20),
        ),
    ]
