# Generated by Django 2.0 on 2018-03-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0029_auto_20180308_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='numeric_code',
            field=models.IntegerField(default=-1),
        ),
    ]
