# Generated by Django 2.0 on 2018-03-09 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0030_auto_20180308_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainclassification',
            old_name='tag',
            new_name='interpret_tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='key',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='trainclassification',
            name='predict_tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='classification_predict', to='madmex.Tag'),
        ),
    ]
