# Generated by Django 2.0.3 on 2018-03-21 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0031_auto_20180309_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentationInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(default='', max_length=200)),
                ('datasource', models.CharField(default='', max_length=200)),
                ('parameters', models.CharField(default='', max_length=200)),
                ('datasource_year', models.CharField(default='2015', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='trainclassification',
            name='interpret_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpret_tag', to='madmex.Tag'),
        ),
        migrations.AlterField(
            model_name='trainclassification',
            name='train_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_object', to='madmex.TrainObject'),
        ),
        migrations.AddField(
            model_name='predictobject',
            name='segmentation_information',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='madmex.SegmentationInformation'),
        ),
    ]
