# Generated by Django 2.0.3 on 2018-03-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0032_auto_20180321_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentationinformation',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
