# Generated by Django 2.0.3 on 2018-04-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0033_segmentationinformation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
