# Generated by Django 2.0.3 on 2018-04-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0035_predictclassification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictclassification',
            name='confidence',
            field=models.FloatField(default=-1.0),
        ),
    ]
