# Generated by Django 2.0.5 on 2018-05-05 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0036_predictclassification_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_id', models.CharField(default=None, max_length=50, unique=True)),
                ('landsat_product_id', models.CharField(default=None, max_length=50, unique=True)),
                ('acquisition_date', models.DateTimeField(default=None)),
                ('day_night', models.CharField(default=None, max_length=50)),
                ('image_quality', models.IntegerField(default=-1)),
                ('cloud_cover', models.FloatField(default=-1.0)),
                ('min_lat', models.FloatField(default=-1)),
                ('min_lon', models.FloatField(default=-1)),
                ('max_lat', models.FloatField(default=-1)),
                ('max_lon', models.FloatField(default=-1)),
                ('footprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madmex.Footprint')),
            ],
        ),
    ]
