# Generated by Django 2.0.6 on 2018-06-06 23:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0038_remove_scene_day_night'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_set', models.CharField(default='', max_length=100)),
                ('interpretation_year', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='ValidObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('validation_tags', models.ManyToManyField(through='madmex.ValidClassification', to='madmex.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='validclassification',
            name='valid_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madmex.ValidObject'),
        ),
        migrations.AddField(
            model_name='validclassification',
            name='valid_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madmex.Tag'),
        ),
    ]
