# Generated by Django 2.0.6 on 2018-06-13 22:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0039_auto_20180606_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(default='', max_length=100)),
                ('validation', models.CharField(default='', max_length=100)),
                ('region', models.CharField(default='', max_length=100)),
                ('scheme', models.CharField(default='', max_length=100)),
                ('n_val', models.IntegerField(default=-1)),
                ('n_pred', models.IntegerField(default=-1)),
                ('overall_acc', models.FloatField(default=1.0)),
                ('report', django.contrib.postgres.fields.jsonb.JSONField()),
                ('comment', models.CharField(default='', max_length=500)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
