# Generated by Django 2.0.3 on 2018-06-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0041_auto_20180613_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='image_quality',
        ),
    ]
