# Generated by Django 2.0.3 on 2018-06-19 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0042_remove_scene_image_quality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='cloud_cover',
            new_name='cloud_cover_land',
        ),
    ]
