# Generated by Django 2.0.3 on 2018-06-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0043_auto_20180619_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='cloud_cover',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='scene',
            name='cloud_cover_land',
            field=models.FloatField(default=100.0),
        ),
    ]
