# Generated by Django 2.0.3 on 2018-06-26 20:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0044_auto_20180619_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_name', models.CharField(default='', max_length=100)),
                ('post_name', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_pre', models.IntegerField(default=-1)),
                ('year_post', models.IntegerField(default=-1)),
                ('algorithm', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madmex.ChangeInformation')),
            ],
        ),
        migrations.AddField(
            model_name='changeclassification',
            name='change_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madmex.ChangeObject'),
        ),
        migrations.AddField(
            model_name='changeclassification',
            name='post_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tag', to='madmex.Tag'),
        ),
        migrations.AddField(
            model_name='changeclassification',
            name='pre_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_tag', to='madmex.Tag'),
        ),
    ]
