# Generated by Django 2.0.3 on 2018-07-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0045_auto_20180626_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeclassification',
            name='name',
        ),
        migrations.AddField(
            model_name='changeinformation',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
