# Generated by Django 2.0.6 on 2018-08-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0046_auto_20180706_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(default='', max_length=150),
        ),
    ]
