# Generated by Django 2.1.5 on 2019-02-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0047_auto_20180830_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictobject',
            name='prediction_tags',
        ),
        migrations.AddField(
            model_name='predictclassification',
            name='features_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='predictobject',
            name='path',
            field=models.CharField(default='', max_length=400),
        ),
    ]
