# Generated by Django 2.1.5 on 2019-02-15 00:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0048_auto_20190211_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
        migrations.AlterField(
            model_name='region',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
