# Generated by Django 2.1.5 on 2019-03-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0051_auto_20190215_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='validobject',
            name='filename',
            field=models.CharField(default='', max_length=200),
        ),
    ]
