# Generated by Django 2.1.5 on 2019-03-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0053_auto_20190308_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationresults',
            name='classification',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='validationresults',
            name='validation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
