# Generated by Django 2.1.5 on 2019-03-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0054_auto_20190311_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictclassification',
            name='features_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
