# Generated by Django 2.1.5 on 2019-03-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0055_auto_20190313_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictclassification',
            name='features_id',
            field=models.IntegerField(default=-1),
        ),
    ]
