# Generated by Django 2.1.5 on 2019-05-03 15:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0056_auto_20190313_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footprint',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
