# Generated by Django 2.2.5 on 2019-10-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0058_auto_20190514_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictobject',
            name='path',
            field=models.CharField(default='', max_length=400, unique=True),
        ),
    ]
