# Generated by Django 2.1.5 on 2020-01-17 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0059_auto_20191001_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainClassificationLabeledByApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_set', models.CharField(default='', max_length=100)),
                ('interpreted', models.BooleanField(default=False)),
                ('automatic_label_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madmex.Tag')),
                ('institution', models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, to='madmex.Institutions')),
                ('interpret_tag', models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interpret_tag_app', to='madmex.Tag')),
                ('train_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_object_app', to='madmex.TrainObject')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='trainclassificationlabeledbyapp',
            name='user',
            field=models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, to='madmex.Users'),
        ),
    ]
