# Generated by Django 2.1.5 on 2020-02-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0060_auto_20200117_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogTrainingSetForApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSetAndODCTilesForApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odc_tile', models.CharField(default='', max_length=10)),
                ('training_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madmex.CatalogTrainingSetForApp')),
            ],
        ),
        migrations.AlterField(
            model_name='trainclassificationlabeledbyapp',
            name='training_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madmex.CatalogTrainingSetForApp'),
        ),
    ]
