# Generated by Django 2.1.5 on 2020-02-24 22:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0062_trainclassificationlabeledbyapp_odc_tile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsetandodctilesforapp',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
