# Generated by Django 2.1.5 on 2020-03-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0063_trainingsetandodctilesforapp_the_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogtrainingsetforapp',
            name='scheme',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
