# Generated by Django 2.1.5 on 2020-03-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0064_catalogtrainingsetforapp_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
