# Generated by Django 2.1.5 on 2020-03-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madmex', '0065_auto_20200312_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
